server:
  port: 8088
  servlet:
    context-path: /demo-service
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ksm_core_user
    username: postgres
    password: postgres
  liquibase:
    enabled: 'true'
    drop-first: 'false'
    change-log: classpath:db/changelog/changelog-0.0.1.xml
    parameters:
      liquibase.changelogLockWaitTimeInMinutes: 20
  jpa:
    hibernate:
      ddl-auto: update
    searchPath: